# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  test-npm:
    type: npm-registry
    url: https://mill.jfrog.info:12191/artifactory/api/npm/test-npm
    token: ${{secrets.TOKEN}} 
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    registries:
      - test-npm
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"


 

